trigger_number: '211211549'       # GRB Name
T90: 34.3046                    # T90 duration of the GRB
T0: 0                             # Trigger time T0 (seconds)
file_path: '/path/to/your/lightcurve/data/.npz file ' # Path where .npz file is located 
output_path: '/path/to/your/output/'   # Path to save analysis results and d
## Advance parameters #######
cores: 2                          # Number of CPU cores for parallel processing
start_padding: 5                  # Factor for extending analysis range before T0 (factor * delt)
end_padding: 5                    # Factor for extending analysis range after T90 (factor * delt)
bw: 0.0001                        # Base light curve bin width (seconds) for data processing
delt: 1.0                         # MVT search window width Delta (seconds) for a specific run, or initial for scan
N: 30                             # Number of Monte Carlo iterations for MVT finding
f1: 5                             # Factor for lower bound of fitting range (f1 * MVT_moving_avg_min)
f2: 3                             # Factor for upper bound of fitting range (f2 * MVT_moving_avg_min)
#all_delta: False                  # If True, runs for all valid_deltas; otherwise, uses specific delt or binary search logic (as per main script's logic)
all_fig: False                     # If True, generates detailed diagnostic d for each iteration (controlled by MVTAnalyzer)