trigger_number: '211211549'
background_intervals: [[-11.67, -1.04], [57.5, 69.58]]
T90: 34.3046
det_list: [n2, na]
bw: 0.0001
delt: 1.0
T0: 0
start_padding: 5
end_padding: 5
N: 30
f1: 5
f2: 3
en_lo: 10
en_hi: 1000
cores: 2
data_path: '/Users/sbala/work/gdt_dev2/mvt/'
output_path: '/Users/sbala/work/gdt_dev2/mvt/'